const FillTextActionTypes = {
  FETCH_FILL_TEXT_DATA_START: 'FETCH_FILL_TEXT_DATA_START',
  FETCH_FILL_TEXT_DATA_SUCCESS: 'FETCH_FILL_TEXT_DATA_SUCCESS',
  FETCH_FILL_TEXT_DATA_FAILURE: 'FETCH_FILL_TEXT_DATA_FAILURE',
};

export default FillTextActionTypes;
